/* eslint-disable no-mixed-operators */
const SECOND = 1000;

const CONNECTION_REFUSED_BY_SERVER = 'ECONNREFUSED';
const SERVER_NOT_FOUND = 'ENOTFOUND';
const CHECK_URLS = ['https_server_address', 'http_server_address'];

const BLOCK_REWARDS_PART = 0.25;
const VOTE_REWARDS_PART = 0.75;
const EXPECTED_PRODUCED_BLOCK_FOR_DAY_NUMBER = 2 * 60 * 60 * 24;
const ACTIVE_PRODUCERS_NUMBER = 21;

const CALCULATE_REWARDS_FOR_DAY_INTERVAL = 30 * SECOND;
const DAY = SECOND * 60 * 60 * 24;
const EXPECTED_CALCULATING_TIMES_FOR_DAY = DAY / CALCULATE_REWARDS_FOR_DAY_INTERVAL;

const ONE_HOUR = SECOND * 60 * 60;

const BULK_WRITE_LIMIT = 100000;

const BLOCKS_NUMBER_IN_PRODUCING_LOOP = 12;

const GAP_BETWEEN_PRODUCING_LOOP = (6 * 21) + 20; // https://trello.com/c/y8ZD1Kyy/69-catch-missed-producing-and-mark-by-color-if-node-is-in-top-21-is-in-approved-schedule-cleos-get-schedule-and-do-not-produced-mor

const MINIMUM_CHANGED_POSITION_FOR_RELOADING = 150;

const MAX_TRANSACTION_PACK_LENGTH = 100;

const BLOCK_CHART_PERIOD = SECOND * 60 * 10;

const RESTORE_BLOCK_CHART_INTERVAL = SECOND * 60;

const KILOBYTE = 1024; // BYTES

module.exports = {
  ACTIVE_PRODUCERS_NUMBER,
  BLOCKS_NUMBER_IN_PRODUCING_LOOP,
  BLOCK_REWARDS_PART,
  BULK_WRITE_LIMIT,
  CALCULATE_REWARDS_FOR_DAY_INTERVAL,
  CHECK_URLS,
  BLOCK_CHART_PERIOD,
  CONNECTION_REFUSED_BY_SERVER,
  DAY,
  EXPECTED_PRODUCED_BLOCK_FOR_DAY_NUMBER,
  EXPECTED_CALCULATING_TIMES_FOR_DAY,
  GAP_BETWEEN_PRODUCING_LOOP,
  ONE_HOUR,
  RESTORE_BLOCK_CHART_INTERVAL,
  KILOBYTE,
  MAX_TRANSACTION_PACK_LENGTH,
  MINIMUM_CHANGED_POSITION_FOR_RELOADING,
  SECOND,
  SERVER_NOT_FOUND,
  VOTE_REWARDS_PART,
};
