// Types
export default Object.freeze({
  FETCHING_ACCOUNT_INFO: 'FETCHING_ACCOUNT_INFO',
  FETCHING_ACCOUNT_INFO_SUCCESS: 'FETCHING_ACCOUNT_INFO_SUCCESS',
  FETCHING_ACCOUNT_HISTORY: 'FETCHING_ACCOUNT_HISTORY',
  FETCHING_ACCOUNT_HISTORY_SUCCESS: 'FETCHING_ACCOUNT_HISTORY_SUCCESS',
  FETCHING_BLOCK_INFO: 'FETCHING_BLOCK_INFO',
  FETCHING_BLOCK_INFO_SUCCESS: 'FETCHING_BLOCK_INFO_SUCCESS',
  FETCHING_TX_INFO: 'FETCHING_TX_INFO',
  FETCHING_TX_INFO_SUCCESS: 'FETCHING_TX_INFO_SUCCESS',
});
