export default Object.freeze({
  FETCH_PRODUCERS_SUCCESS: 'Producers/FETCH_PRODUCERS_SUCCESS',
  PRODUCERS_UPDATE: 'Producers/PRODUCERS_UPDATE',
  TOGGLE_PRODUCER_SELECTION: 'Producers/TOGGLE_PRODUCER_SELECTION',
  SET_FILTER_INPUT_VALUE: 'Producers/SET_FILTER_INPUT_VALUE',
});
