// Types
export default Object.freeze({
  // Modal
  SET_MODAL_DATA_FETCHING_STATE: 'SET_MODAL_DATA_FETCHING_STATE',
  SET_MODAL_STATE: 'SET_MODAL_STATE',
  // Table
  SET_TABLE_COLUMN_STATE: 'SET_TABLE_COLUMN_STATE',
  RESET_COLUMNS_VISIBILITY: 'RESET_COLUMNS_VISIBILITY',
});
