export default Object.freeze({
  LAST_BLOCK_STATS_UPDATE: 'GeneralStats/LAST_BLOCK_STATS_UPDATE',
  TPS_APS_STATS_UPDATE: 'GeneralStats/TPS_APS_STATS_UPDATE',
  TOTAL_STACKED_UPDATE: 'GeneralStats/TOTAL_STACKED_UPDATE',
  CONNECTED_USERS_UPDATE: 'GeneralStats/CONNECTED_USERS_UPDATE',
});
